### ISSUE TITLE
No message is shown when no bags are equipped and inventory is opened

### ISSUE THREAD

**Issue by echads** [michaelday008/AnyRPGCore#11]
The InventoryCanvas doesn't work in the current build. Pushing "B" doesn't open it. Upon reviewing it in the Hierarchy I can see that it isn't setup as a Window like the rest of the UI. Bags still seem to work though. Also pushing "I" doesn't open up the Currency panel. I will create another issue for that. https://github.com/michaelday008/AnyRPGCore/issues/12

**Comment by communityus** [comment]
B is what opens Bag, so I think that part is working as expected. Currency one still remains.

**Comment by michaelday008** [comment]
If you are playing the Lost Soul example/demo, you will have to first collect a backpack and equip it before you can open it.  This is done by completing the quest from the Vendor in Birch Grove.  If you press B before that point, nothing will happen because no bags are equipped.

I admit this isn't really obvious, and probably some message should be displayed on screen telling the player "You have no bags equipped" so they at least know that the system accepted their key press.

**Comment by michaelday008** [comment]
On screen message has been added to let the player know that no bags are equipped when Inventory is toggled.
This change is now in the master branch.
