### ISSUE TITLE
One Handed Sword - B to C

### ISSUE THREAD

**Issue by communityus** [michaelday008/AnyRPGCore#14]
Grabbing the sword from the table, then trying to grab it from your bag and put it in the hand slot on the Character screen will cause the sword to vanish since we don't have the One Handed skill.

**Comment by communityus** [comment]
https://github.com/michaelday008/AnyRPGCore/issues/13

**Comment by michaelday008** [comment]
I was able to re-create this by loading a character made in a previous version of AnyRPG.  

This is expected because in the latest version, the weapon skills and armor skills for the warrior are filtered by Unit Type (humanoid).  Since previous versions used a common Unit Profile (DefaultUMAPlayer), and the newer versions use UMABody (at least for A Lost Soul), any character saved with a previous version will be referencing the old Unit Profile, which isn't humanoid any more, and therefore won't have those weapon skills.

At this point, there is a good deal of breakage expected between releases as a lot of non backward compatible changes are being made.  You could theoretically fix this by using the character creator to re-save your appearance which should give you the correct Unit Profile, but at this early stage, you'll probably have less issues if you don't use save files from old versions.

Once this project is out of alpha and reaches release stage, there should be much fewer (if any) backward compatibility issues.
