### ISSUE TITLE
move field type from base QuestObjective to implemented classes

### ISSUE THREAD

**Issue by nothingTVatYT** [michaelday008/AnyRPGCore#34]
Currently the name of a resource is in the base class and because implementations can use it for different resource types we cannot add a resource selector attribute. Adding a field in the implemented classes would fix that.

**Comment by michaelday008** [comment]
This work is now in progress.
Selectors have been added for everything except:
-Kill objectives (because they can reference a faction or character)
-Use Interactable objectives because they can reference an interactable option or an interactable, both of which can just exist in a scene with no related Scriptable Objects.

**Comment by michaelday008** [comment]
This work is now complete in the latest master
