### ISSUE TITLE
A lot of errors and pink textures when trying to convert project to hdrp

### ISSUE THREAD

**Issue by nigelmerle** [michaelday008/AnyRPGCore#68]
-Please note that HDRP uses the linear  instead of gamma, hence all uma character appear with bright colors in character selection screen
-character selection screen is unselectable in hdrp mode
-I found a lot of uma textures went pink, im not quite sure what to do next
-I tried several times to reinstall anyrpg, 
-when I try to create a new game with wizard, it didnt worked
-When I did a search there was around 75 broken links, i suppose anyrpg didnt upload all the packages correctly, so this time i will try to download anyrpg from github, i hope all the assets get imported this time...but i think overall i will need help concerning compatibility of anyrpg with hdrp...that would be too bad not to take advantage of hdrp because i have plans to build my levels quickly with gaia

**Comment by michaelday008** [comment]
The issues you describe are not issues specific to AnyRPG.  They are issues with HDRP in general.  You will get some pink textures when you convert to URP also.  That just means that the Unity HDRP material conversion didn't assign the proper shader to a certain material.  You can search youtube for videos showing how to do URP / HDRP conversion and fix pink materials.

UMA has it's own URP converter.  You will have to use that option also.  You can ask on the UMA discord about HDRP.

**Comment by nigelmerle** [comment]
Do you advise me to use URP ?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by michaelday008** [comment]
Neither HDRP nor URP are supported yet.  Basically, you can use whichever one you want, but you won't be able to upgrade your AnyRPG version if you use one because the materials will all be changed by the conversion, and upgrading would just set them back to the built-in pipeline versions.

Unity really messed things up with their implementation of URP and HDRP because they dropped support for the built-in rendering pipeline when all of its features don't exist in the SRP.  It makes it especially tough for a project like AnyRPG because of there is quite literally no way I know of to release anything that is compatible with both because using one or the other converts all the materials.

**Comment by michaelday008** [comment]
I'm closing this issue since neither HDRP nor URP are supported, so you are on your own if you want to try to get them working.

**Comment by nigelmerle** [comment]
Ok thank you for the explanation, if i cant get neither work i will stick to the default built in pipeline. I created three projects and i an testing each one of them to experiment...i am sure there must be some kind if ways to achieve the same level of graphic with the built in pipeline, need to play with post processing and lighting probably.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
