### ISSUE TITLE
Please make a layers of abstractions for your hard code implementation of Databse/Multiplayer/Events!

### ISSUE THREAD

**Issue by studentutu** [michaelday008/AnyRPGCore#7]
You are doing a monkey job.
To avoid it - please make a layer of abstraction for Multiplayer System.
Add EventBus messanger to avoid hard coded events/classes
Please do not use Resources as your primary source of assets! It will be a neightmare to debug stuff with them.

**Comment by michaelday008** [comment]
I just saw this comment now.

Abstraction will definitely be added for multiplayer in the future.  I haven't done any work with Unity multiplayer before though so at this point I'm not sure what that abstraction should even look like.

You can see the SystemEventManager is now starting to use a non-hard-coded event system.  More events will be migrated to this system over time.

Resources were used originally because there is nothing worse than getting a Unity package from the Asset store and being required to spend a bunch of time learning whatever DB system the author chose and setup a database server before even being able to play.  DB support will be used eventually when network support is added, but the goal of this package is that it 'just works' out of the box.

This request isn't really actionable is it contains multiple items that would each need to be individually tracked.  If you have a specific use case for these features, feel free to open individual requests for each of them and describe the use case in more detail.
