### ISSUE TITLE
Cannot convert blend file to fbx in  unity

### ISSUE THREAD

**Issue by nigelmerle** [michaelday008/AnyRPGCore#71]
There is a technical bug in unity where unity cannot convert the dragon blend file to fbx. I had blender 3.0 and i was forced to install blender version 2.80. Now unity is converting the blend file. The people need to be aware of it or else  the dragon mount appear invisible in game

**Comment by SickaGamer** [comment]
Maybe it's because you always using a crack version of Unity...

**Comment by nigelmerle** [comment]
I dont think that a crack is the problem though. I think i was using unity LTS perhaps thats why it wasn't working, i never had problems with crack in my life.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by nigelmerle** [comment]
I still dont know the difference between unity lts and the technician version. But in your tutorials i saw that you downloaded the technician version. Im confused with this unity, so many versions they make and i spend most of my time fixing the bugsOn Dec 20, 2021 05:28, SickaGamer ***@***.***> wrote:

Maybe it's because you always using a crack version of Unity...

**Comment by michaelday008** [comment]
Thanks for filing this report.  I'll see about exporting the dragon to an FBX so it's not dependent on blender.

**Comment by nigelmerle** [comment]
Thank you , oh and i found out that gaia can use the built renderer of unity, thats awesome because i won't have to convert my project to hdrp. The built is renderer is quite decent, i think it looks better than urp.


Cheers

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by nigelmerle** [comment]
Hello I reinstalled the unity free version and I just finished reinstalling anyrpg but I noticed in the build setting there is a lot of empty scenes it says deleted.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by michaelday008** [comment]
> Hello I reinstalled the unity free version and I just finished reinstalling anyrpg but I noticed in the build setting there is a lot of empty scenes it says deleted.

The deleted scenes are expected for now.  In AnyRPG 0.13a Unity package, you shouldn't see those.  In the github version of the project, you will see some.  This is an artifact of the way that Unity handles its build settings and there isn't really a good way around this for now.

If build settings are not included, levels will fail to load unless people manually add them to their build settings.  Since I want this project to work out of the box without a bunch of setup, they have to be included.  It's too much work to maintain 2 copies of the project (a github version and a unity package version) because I would spend all day re-adding build settings and making sure they are in sync, so all development is done in the Unity package version of the project.  When things are committed to git, that includes the Unity package build settings, which includes the references to the extra scenes in the Lost Soul demo game.

**Comment by nigelmerle** [comment]
But anyrpg 0.13a is not yet available  on the anyrpg website i just checked. I downloaded the one on github meanwhile, do you have a release date yet


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by nigelmerle** [comment]
I see some cool features coming

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by michaelday008** [comment]
> But anyrpg 0.13a is not yet available on the anyrpg website i just checked.

The deleted scenes will not cause any problem or error.  It's fine to use the Unity package or github version with them there.

**Comment by michaelday008** [comment]
> I downloaded the one on github meanwhile, do you have a release date yet

As always, it will be released when testing is complete, and there are no more bugs found during testing.

**Comment by michaelday008** [comment]
The dragon in the git project has been replaced with an FBX, so blender should no longer be required to properly import it.

All blend files in the Engine (that gets exported to the Unity package) have also been replaced with FBX files.

The prefabs that referenced the meshes in the blend files have also been updated so the changes should be transparent to end users when the AnyRPG 0.13a Unity package is released.  The only exception to this is the rope fence.  The default scale and position of the rope fence has been adjusted to a scale of 1, instead of 0.25, so any rope fences may need to be repositioned in scenes
